name: Run Telegram Bot

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          ADMIN_USER_IDS: ${{ secrets.ADMIN_ID }}
        run: python telegram_bot.py
